name: Wine-Mono CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name : Ignore packages require EULA
      run: sudo apt-mark hold msodbcsql17
    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade -y 
        sudo apt-get install wine-stable -y
    - name: Install Make Tools
      run: sudo apt-get install cmake -y
    - name: Clone submodules
      run: git submodule submodule update --init --recursive --depth=1
    - name: make msi
      run: make msi
    - name: make targz
      run: make targz

