name: Wine-Mono CI

on:
  push:
    branches: [ develop, ci ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up
      run: |
        sudo apt-get update
        # && sudo apt-get upgrade -y 
        # sudo apt-get build-dep mono-runtime
        sudo apt-get install wine -y
    - name: make msi
      run: make msi
    - name: make targz
      run: make targz

