name: Wine-Mono CI

on:
  push:
    branches: [ develop,cygwin ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:


  win-build-upstream-mono:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: git unzip
      - name: check env
        shell: C:\tools\cygwin\bin\bash.EXE --noprofile  -e -o pipefail {0}
        run: |
          ls
          pwd
          ls -a
          
      - name: Download upstream mono
        run: git clone --depth=1 --recursive https://github.com/mono/mono.git

      - name: Build native Mono
        run: |
          cd mono
          export PREFIX=$(pwd)/build_mono
          ./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --disable-boehm
          make get-monolite-latest
          make -j$(nproc)
          make install
      - name: Mono test
        run: cd mono && make check -j$(nproc)
   

