name: Wine-Mono CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:


  win-build-upstream-mono:
    runs-on: windows-2019
    defaults:
      run: 
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
          echo "::set-output name=time::$(/bin/date -u "+%H%M%S")"
        shell: bash
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-cygwin-packages
        with:
          path: C:\\tools\\cygwin\\packages
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-${{ steps.get-date.outputs.time }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-${{ steps.get-date.outputs.time }}
            ${{ runner.os }}-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: git unzip

      - name: Download upstream mono
        run: exit 1 && git clone --depth=1 --recursive https://github.com/mono/mono.git

      - name: Build native Mono
        run: |
          cd mono
          export PREFIX=$(pwd)/build_mono
          ./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --disable-boehm
          make get-monolite-latest
          make -j$(nproc)
          make install
      - name: Mono test
        run: cd mono && make check -j$(nproc)
   

