name: Wine-Mono CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Remove packages require EULA
      run: sudo apt remove msodbcsql17 linux-azure linux-cloud-tools-azure linux-headers-azure linux-image-azure linux-tools-azure -y
      #run: sudo apt-mark hold msodbcsql17
    - name: Install gnupg
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y 
        sudo apt install gnupg ca-certificates -y
    - name: Fix Yarn Key (https://github.com/yarnpkg/yarn/issues/7866)
      run:  |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
    - name: Install Wine
      run: |
        #wget -nc https://dl.winehq.org/wine-builds/winehq.key
        #sudo apt-key add winehq.key
        #sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 
        #sudo apt-get update -y
        #sudo dpkg --add-architecture i386 
        sudo apt-get update
        sudo apt-get upgrade -y 
        #sudo apt install --install-recommends wine-stable wine32 -y
        #sudo dpkg --print-foreign-architectures
        #sudo dpkg --print-architecture
        sudo apt install --install-recommends wine64 wine64-tools
    - name: Install Mono Build Dependencies
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt-get install mono-devel mono-complete libtool-bin gettext cmake -y
        # Seems that Github Action Image already includes mono-devel. Still install it explicitly
 #   - name: Clone submodules
  #    run: git submodule update --init --recursive --depth=1
    - name: Check Environment
      run: |
        gcc --version
        g++ --version
        # i686-w64-mingw32-gcc --version
        wine --version
        mono --version
        ld --version
        cmake --version
        man libtool | tail -1
    - name: make msi
      run: make msi
    - name: make targz
      run: make targz
    - name: Install
      run: wine msiexec /i winemono.msi
    - name: Test
      run: make test
        

